---
# LICENSE:         Public Domain

#    ansible-playbook ad-hoc/info/show-ansible-facts-local.yml -i hosts
#    ansible all -m setup -a "filter=ansible_local" -i hosts

# To print facts with this playbook, use:
#    ansible-playbook show-ansible-facts-local.yml -i hosts

# To use Ansible Ad Hoc command (does not need this playbook), use
#    ansible all -m setup -a "filter=ansible_local" -i hosts

- name: "ansible-ad-hoc | show-ansible-facts-local.yml"
  hosts: all
  tasks:
    - name: "ansible-ad-hoc | show-ansible-facts-local | "
      setup:
        filter: "ansible_local"
        gather_subset:
          - '!all'
          - '!min'
          - 'facter'
    - debug:
        msg: "{{ ansible_facts['ansible_local'] }}"
